services:
  postgres:
    image: postgres:16
    container_name: crypto-postgres-v2
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: crypto
    ports:
      - "55432:5432"                # host:container (si elegiste 55432)
    volumes:
      - pgdata_v2:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.2-python3.11
    container_name: crypto-airflow-v2
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      environment:
      # 👇 pasa las credenciales/params al contenedor
      COINGECKO_API_KEY: ${COINGECKO_API_KEY}
      COINGECKO_COINS: ${COINGECKO_COINS}
      COINGECKO_VS: ${COINGECKO_VS}
      # ¡Interno entre contenedores SIEMPRE 5432!
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://app:app@postgres:5432/crypto
    command: ["standalone"]         # 👈 arregla el “GROUP_OR_COMMAND” faltante
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: crypto-superset-v2
    depends_on:
      - postgres
    environment:
      SUPERSET_ENV: production
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    ports:
      - "8090:8088"

volumes:
  pgdata_v2: {}